# Generated by Django 4.1.1 on 2022-09-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_student_marks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student", name="Marks", field=models.IntegerField(null=True),
        ),
    ]
