# Generated by Django 3.2 on 2022-09-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
